spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibername:
      ddl-auto: create
    properties:
      hibername:
#        show_spl: true
        format_sql: true

logging:
  lebel:
    org.hibername.SQL: debug